name: API Deploy Pipeline
on:
    push:
        paths:
            - 'app/**'

jobs:
  say-hello:
    name: Print Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"